### ISSUE TITLE
Object Magnets - Page : 221 || Mistake

### ISSUE THREAD

**Issue by adityathebe** [bethrobson/Head-First-JavaScript-Programming#11]
In the last statement it's written dog.bark which refers to the "bark" property of the object "dog". I think it's supposed to be the variable "bark" instead of "dog.bar". Isn't it?

**Comment by bethrobson** [comment]
That was fixed in a second printing. Use the errata page to see errors that are still outstanding and those that have been fixed:

http://www.oreilly.com/catalog/errata.csp?isbn=0636920027065
