### ISSUE TITLE
Object Magnets Solution (pg. 221)

### ISSUE THREAD

**Issue by tygamchenry** [bethrobson/Head-First-JavaScript-Programming#19]
The speak variable is incorrect in the book. The correct solution is the following:

var speak = dog.name + " says " +  bark + " when he wants to " + dog.activity;
console.log(speak);

Should print out in the console: Fido says WOOF WOOF when he wants to fetch balls

It can't be dog.bark because the bark variable isn't assigned to the dog object. We're finding out what the bark variable would be with this specific (dog) object.

**Comment by bethrobson** [comment]
Yes that's fixed in errata.
