### ISSUE TITLE
object name

### ISSUE THREAD

**Issue by pirooz-pakdel** [bethrobson/Head-First-JavaScript-Programming#22]
Hi 
In  an array of Objects like the one for  (  Head-First-JavaScript-Programming/chapter10/plane.html  ) the plane problem, is the singular variable (i.e. PASSENGER) the default variable name for each object in the PASSENGERS array of objects? or does it get designated by default once we use it?
I ask because I see no variable passenger defined anywhere but it is used in the functions to check on the no fly list, has/has not paid etc. What is the convention here? I probably would have opted for this.passengers [x].paid for example instead of passenger.paid as used. Where or who defined singular passenger as the variable to use?
I apologize if what I am asking is too trivial but it has me confused.
thanks for all assistance.
Pirooz

**Comment by bethrobson** [comment]
On line 130, we pass the array passengers into the function servePassengers, which loops through the array, and calls serveCustomer on each item in the array. So one passenger is passed into serveCustomer and assigned to the parameter passenger. That is how passenger is assigned a value from the array (one passenger). 

Review the functions chapter to see how arguments and parameters work. 

Hope that helps!

**Comment by pirooz-pakdel** [comment]
Many thanks indeed.
