### ISSUE TITLE
Appendix RegExp, Recursion and JS Algorithms Practice

### ISSUE THREAD

**Issue by SOSANA** [bethrobson/Head-First-JavaScript-Programming#7]
Hi Beth,

I was curious if you had any recommendations for practicing and studying RegExp and Recursion in greater detail. Hoping you could point me in the right direction for a resource on a good book, a blog, or online tutorial that goes into greater detail to really hone my Javascript chops and have more practice with this. 

Also I really loved the "ah ha moments" I had when walking through and applying some of the various algorithms throught the book. I'll be honest feel a bit lost I know there are 100's if not 1000's of algorithms but I don't know where I can find a complete resource on all or majority of common algorithms used for javascript. I keep telling myself wait till you run into a problem than search for a common algorithm that pertains to the problem i encounter in the future, but what if I could just refer to a list, that I could see possible algorithms that I could use in the future?

Thanks again and firm believer in practice practice practice :)

**Comment by SOSANA** [comment]
I found it for anyone else looking in future, full list of algorithm javascript challenges :) ...coder byte http://coderbyte.com/CodingArea/Challenges/

**Comment by bethrobson** [comment]
Hey Zach, yes, coderbyte is great for practicing. As far as algorithms go, many algorithms (not all, but most) are language independent. So studying algorithms in general is always a good idea for improving your skills in that area.

Stackoverflow is also a great resource for finding solutions to specific problems.
